# Generated by Django 5.2.8 on 2026-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization/School Name')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Position/Role')),
                ('preferred_date', models.DateField(verbose_name='Preferred Demo Date')),
                ('preferred_time', models.TimeField(verbose_name='Preferred Time')),
                ('duration', models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='45', max_length=3, verbose_name='Demo Duration')),
                ('purpose', models.CharField(choices=[('student', 'Student/Parent'), ('teacher', 'Teacher/Educator'), ('school', 'School Administration'), ('corporate', 'Corporate Training'), ('other', 'Other')], default='teacher', max_length=20, verbose_name='Purpose of Demo')),
                ('participant_count', models.PositiveIntegerField(default=1, help_text='Number of people attending the demo', verbose_name='Expected Participants')),
                ('special_requirements', models.TextField(blank=True, help_text="Any specific topics you'd like us to cover", null=True, verbose_name='Special Requirements/Questions')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='I agree to be contacted regarding this demo')),
                ('booking_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demo Booking',
                'verbose_name_plural': 'Demo Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
