# Generated by Django 5.2.8 on 2026-01-13 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_type', models.CharField(choices=[('personal', 'Personal Demo'), ('team', 'Team Demo (2-5 people)'), ('enterprise', 'Enterprise Demo (5+ people)')], default='personal', max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('timezone', models.CharField(choices=[('EST', 'Eastern Time (EST)'), ('CST', 'Central Time (CST)'), ('MST', 'Mountain Time (MST)'), ('PST', 'Pacific Time (PST)'), ('GMT', 'GMT/UTC')], default='EST', max_length=50)),
                ('interest_area', models.CharField(choices=[('k12', 'K-12 Education'), ('higher_ed', 'Higher Education'), ('corporate', 'Corporate Training'), ('language', 'Language Learning'), ('test_prep', 'Test Preparation'), ('other', 'Other')], default='k12', max_length=20)),
                ('specific_requirements', models.TextField(blank=True, help_text='What specific features or use cases are you interested in?', null=True)),
                ('current_system', models.CharField(blank=True, choices=[('none', 'No current system'), ('moodle', 'Moodle'), ('canvas', 'Canvas'), ('blackboard', 'Blackboard'), ('other_lms', 'Other LMS'), ('custom', 'Custom solution')], max_length=20, null=True)),
                ('number_of_users', models.IntegerField(blank=True, help_text='Estimated number of potential users', null=True)),
                ('lead_source', models.CharField(choices=[('website', 'Website'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('event', 'Event/Conference'), ('search', 'Search Engine'), ('other', 'Other')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Demo Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('appointment_confirmed', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demo_duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('demo_link', models.URLField(blank=True, help_text='Zoom/Google Meet link', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User account if they were signed in', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Appointment',
                'verbose_name_plural': 'Demo Appointments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_de_email_102778_idx'), models.Index(fields=['status'], name='accounts_de_status_bbfe83_idx'), models.Index(fields=['preferred_date'], name='accounts_de_preferr_687f6a_idx')],
            },
        ),
    ]
