# Generated by Django 5.2.8 on 2026-01-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_demoappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoAppointment',
        ),
    ]
