# Generated by Django 5.2.8 on 2025-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
