# Generated by Django 5.2.8 on 2025-12-22 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignmentprogress_courseprogress_materialview'),
        ('notes', '0003_classmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('author_first_name', models.CharField(help_text="Author's first name", max_length=200)),
                ('author_last_name', models.CharField(help_text="Author's last name", max_length=200)),
                ('additional_authors', models.TextField(blank=True, help_text='Additional authors (comma separated): Smith, J., Johnson, K.', null=True)),
                ('publication_year', models.PositiveIntegerField(help_text='Year of publication (e.g., 2023)')),
                ('edition', models.PositiveIntegerField(default=1, help_text='Edition number (e.g., 5 for 5th edition)')),
                ('publisher', models.CharField(max_length=500)),
                ('isbn', models.CharField(blank=True, help_text='ISBN (International Standard Book Number)', max_length=20, null=True)),
                ('doi', models.URLField(blank=True, help_text='Digital Object Identifier (DOI) URL', null=True)),
                ('url', models.URLField(blank=True, help_text='Direct link to book if available online', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='books/covers/')),
                ('pdf_file', models.FileField(help_text='PDF version of the book (PDF only)', upload_to='books/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Is this book required reading?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Course this book is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='courses.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher who added this book', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
