# Generated by Django 5.2.8 on 2025-12-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='doi',
        ),
    ]
